create table public.bookings (
  id bigint generated by default as identity primary key,
  service text not null,
  booking_date date not null,
  booking_time time not null,
  name text not null,
  phone text not null,
  car text,
  created_at timestamptz not null default now()
);

alter table public.bookings enable row level security;

create policy "Разрешить отправку заявок всем"
  on public.bookings for insert
  to anon, authenticated
  with check (true);

create policy "Разрешить чтение заявок авторизованным"
  on public.bookings for select
  to authenticated
  using (true);
